java -jar blade.jar sh install https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/external/gentyref/1.2.0.vaadin1/gentyref-1.2.0.vaadin1.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/external/gwt/gwt-elemental/2.8.2.vaadin2/gwt-elemental-2.8.2.vaadin2.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-shared/8.17.0/vaadin-shared-8.17.0.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-server/8.17.0/vaadin-server-8.17.0.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-osgi-integration/8.17.0/vaadin-osgi-integration-8.17.0.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-client-compiled/8.17.0/vaadin-client-compiled-8.17.0.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-themes/8.17.0/vaadin-themes-8.17.0.jar
java -jar blade.jar sh install https://repo1.maven.org/maven2/com/vaadin/vaadin-liferay-integration/8.17.0/vaadin-liferay-integration-8.17.0.jar
java -jar blade.jar sh install file:/Users/rostaskrisztian/projects/Vistra/vaadin-test-portlet/target/vaadin-test-portlet-0.1.jar
